### ISSUE TITLE
Prompt before overriding anything in json2kinto

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo2kinto#12]
This script is **supposed** to be run only once to import the existing blocklist entries into a blank server.

But still, it would be safer that it nevers overwrites anything by default.
Especially the collection schemas.

If we change an existing schema in production, and if records are created in a form that is not supported by clients, it could have disastrous consequences :fearful:

**Comment by Natim** [comment]
json2kinto works with a schema that you give on the CLI, you can also run it without schema.

The synchronization never update record, either the record doesn't exists and it gets created either it doesn't exists anymore and gets deleted:

https://github.com/mozilla-services/kinto2xml/blob/master/kinto2xml/synchronize.py#L4-L19

**Comment by Natim** [comment]
> it could have disastrous consequences

The way schema works it only impact new data and not existing data so we are good here.
