### ISSUE TITLE
lxml benefit ?

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/amo2kinto#29]
Why do we use lxml rather that python's sdtlib package ? 

* pros: ?
* cons: major pain point when we build Kinto.

**Comment by Natim** [comment]
Except from the fact that it can handle large XML files. I don't know.

We could try to switch to the Python XML module and see if it fits the need.

**Comment by tarekziade** [comment]
Let's put this on hold for now.

**Comment by Natim** [comment]
``yum install libxslt-devel`` should make it works.

**Comment by Natim** [comment]
Fixed with https://github.com/mozilla-services/svcops/issues/1049
