### ISSUE TITLE
Add versionRange field for Gfx entries

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/amo2kinto#39]
Refs https://github.com/mozilla/addons-server/issues/3054 and [bug 1283601](https://bugzilla.mozilla.org/show_bug.cgi?id=1283601)

> What we need is for gfx entries to have two additional text fields: Max application version, Min application version. They should both be optional. If either has a value, the versionRange node should be added as a child of the `gfxBlacklistEntry`, like in these examples:
>
> ```xml
> <versionRange maxVersion="49.9" />
> <versionRange minVersion="40.0a1" />
> <versionRange minVersion="48.0.2" maxVersion="49.*" />

**Comment by jrmuizel** [comment]
We'd like to get this deployed soon. Do you have an approximate timeline for completing this?

**Comment by Natim** [comment]
It has to be do in addons-server first,

**Comment by jrmuizel** [comment]
Can this part be done now?

**Comment by Natim** [comment]
I think you need to ask that in one of these bugs: refs mozilla/addons-server#3054 and bug 1283601

**Comment by Natim** [comment]
Oh it has https://github.com/mozilla/addons-server/issues/3054 Yes I will be working on it next week.

**Comment by Natim** [comment]
Released in amo2kinto 1.4.0
