### ISSUE TITLE
Do not strip extra fields like name, creator, homepageURL, updateURL

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/amo2kinto#7]
As discussed here, they can be omitted **for now** in the amo ui
https://github.com/mozilla-services/amo-blocklist-ui/issues/35

But in the client we have to be ready to support them from day 1, in case they are added in the ui.
I suggest that we don't strip them when importing.

Which makes wonder how does the UI behaves when a record with some unknown fields are loaded in a form. Are they lost or preserved ?

**Comment by Natim** [comment]
I have no idea, that's probably something we should ask to @n1k0

**Comment by Natim** [comment]
This doesn't work well with the ``additionalProperties: false`` in the schema.
