### ISSUE TITLE
When BadSignatureError happens, kinto-lambda-validate_signature should tell what it tried to validate and failed

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/amo2kinto#78]
We got paged because BadSignatureError happened to kinto-lambda-validate_signature lambda. However when looking into the lambda logs, it is not obvious what the lambda tried to validate and failed.

The error just looks like this.

```
: BadSignatureError
Traceback (most recent call last):
File "/var/task/aws_lambda.py", line 87, in validate_signature
raise exception
File "/var/task/aws_lambda.py", line 74, in validate_signature
signer.verify(serialized, signature)
File "/var/task/kinto_signer/signer/local_ecdsa.py", line 85, in verify
raise BadSignatureError(e)
kinto_signer.signer.exceptions.BadSignatureError
```

The request is that when logging the BadSignatureError,  the validate lambda should also log what it tried to validate and failed. This helps troubleshoot during an incident.

**Comment by Natim** [comment]
It supposed to be the case, can you send the full log? https://github.com/mozilla-services/amo2kinto-lambda/blob/master/aws_lambda.py#L48

**Comment by Natim** [comment]
Let's add the name of the collection it in the traceback itself.

**Comment by bqbn** [comment]
> Let's add the name of the collection it in the traceback itself.

That'd be great. It'll help quickly identify the issue in the middle of an incident. 👍
