### ISSUE TITLE
kinto-lambda-validate_signature fails without error or traceback information

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/amo2kinto#83]
The kinto-lambda-validate_signature sometimes fails without error or traceback information. So far, what we have noticed is that it only happens when checking `/buckets/blocklists/collections/addons` collection, and it logs `Signature KO.` with a few lines of other information. We don't know why this happens or what triggers it at this point. And this seems to be intermittent too, for example it can happen a few times in one hour, and then doesn't happen at all most time of the day (The lambda itself runs every 5 minutes).

And just fyi, if it is a successful run, the lambda logs a single `Signature OK` for each of the input collections.

We've included the logs of one run of the lambda below. Please let us know if there are questions. Thanks!

[lambda.logs.zip](https://github.com/mozilla-services/amo2kinto/files/1787907/lambda.logs.zip)

**Comment by leplatrem** [comment]
Fixed in amo2kinto-lambda
